---
version: "3.3"
services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#            J B O S S E A P  v7.3.0  /  W I L D F L Y  v18.0.1            #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#

#--------------------------------------------------------------------------#
#                       S T A N D A L O N E  M O D E                       #
#--------------------------------------------------------------------------#
    standalone:
        build: ./build
        image: "local/jboss-eap:7.3"
        #image: "local/wildfly:18.0.1"
        ports:
            - "8080:8080"
            - "9990:9990"
        environment:
            - "TZ=Asia/Seoul"   
            - "JAVA_OPTS=-Xms1024m -Xmx1024m -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0 -Djboss.server.default.config=standalone.xml -Djava.net.preferIPv4Stack=true"
        entrypoint: ["./bin/standalone.sh"]   

#--------------------------------------------------------------------------#
#                          D O M A I N  M O D E                            #
#--------------------------------------------------------------------------#
    # master:
    #     build: ./build
    #     image: "local/jboss-eap:7.3"
    #     #image: "local/wildfly:18.0.1"
    #     ports:
    #         - "8080:8080"
    #         - "8180:8180"
    #         - "9990:9990"
    #     environment:
    #         - "TZ=Asia/Seoul"   
    #         - "JAVA_OPTS=-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true"   

    # slave:
    #     build: ./build
    #     image: "local/jboss-eap:7.3"
    #     #image: "local/wildfly:18.0.1"
    #     ports:
    #         - "18080:8080"
    #         - "18180:8180" 
    #     environment:
    #         - "TZ=Asia/Seoul"   
    #         - "JAVA_OPTS=-Xms256m -Xmx512m -Djboss.domain.master.address=master -Djboss.host.default.config=host-slave.xml -Djava.net.preferIPv4Stack=true" 

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                             M A R I A D B  v10.5                         #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#   
    database:
        image: mariadb:10.5
        environment: 
            TZ: "Asia/Seoul"
            MYSQL_ROOT_PASSWORD: jboss
            MYSQL_DATABASE: jbossdb
            MYSQL_USER: jboss
            MYSQL_PASSWORD: jboss
        volumes:
            - ./database/data:/var/lib/mysql:rw 
            - ./database/init:/docker-entrypoint-initdb.d:rw